services:
  db:
    container_name: InventoryService
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ticketing
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
      - db-data:/var/log/mysql

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 3000
    volumes:
      - zookeeper-secrets:/etc/zookeeper/secrets
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  kafka-broker:
    container_name: kafka-broker
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
      - "29092:29092"
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-secrets:/etc/kafka/secrets
      - kafka-data:/var/lib/kafka/data

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8084:8080"
    restart: always
    depends_on:
      - kafka-broker
    environment:
      KAFKA_CLUSTERS_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: kafka-broker:29092
      DYNAMIC_CONFIG_ENABLED: 'true'

  kafka-schema-registry:
    container_name: kafka-schema-registry
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: kafka-schema-registry
    restart: always
    depends_on:
      - kafka-broker
    ports:
      - "8083:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka-broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://kafka-schema-registry:8081
    volumes:
      - kafka-schema-secrets:/etc/schema-registry/secrets

  keycloak-db:
    container_name: keycloak-mysql
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
      - keycloak-db-data:/var/lib/mysql

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.4.4
    ports:
      - "8091:8080"
    restart: always
    command: [ "start-dev", "--import-realm" ]
    depends_on:
      - keycloak-db
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      CUSTOMER_SERVICE_API_URL: http://host.docker.internal:8086/api/v1
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
      - ../KeycloakSpi/target/keycloak-spi-1.0.0.jar:/opt/keycloak/providers/keycloak-spi-1.0.0.jar
      - ../CommonDto/target/common-dto-1.0.0.jar:/opt/keycloak/providers/common-dto-1.0.0.jar

volumes:
  db-data:
    name: inventory_service_db

  zookeeper-secrets:
    name: zookeeper_secrets
  zookeeper-data:
    name: zookeeper_data
  zookeeper-log:
    name: zookeeper_log

  kafka-schema-secrets:
    name: kafka_schema_secrets

  kafka-data:
    name: kafka_data
  kafka-secrets:
    name: kafka_secrets

  keycloak_data:
    name: keycloak_data
  keycloak-db-data:
    name: keycloak_db
